compress_assets: on
gzip_assets: off

javascripts:
  foundation:
    - javascripts/jquery.reveal.js
    - javascripts/jquery.orbit-1.4.0.js
    - javascripts/jquery.customforms.js
    - javascripts/jquery.placeholder.min.js
    - javascripts/jquery.tooltips.js
